gvedit: Fix Windows API to match string data type
This explicitly specifies to use ANSI version of GetModuleFileName API.
Otherwise, the Unicode version was assumed due to UNICODE macro being
defined by Qt moc. This fixes the following compiler error in mingw.

csettings.cpp:105:45: error: cannot convert 'char*' to 'LPWSTR' {aka 'wchar_t*'}
  105 |       rc = GetModuleFileName(NULL, path.data(), path.size());
      |                                    ~~~~~~~~~^~
      |                                             |
      |                                             char*