CMake: add missing ilu library for linking
This fixes the following linker error in mingw

ld.exe: gvdevice_devil:(.text+0xd9): undefined reference to __imp_iluGetInteger
ld.exe: gvdevice_devil:(.text+0x1ed): undefined reference to __imp_iluErrorString
ld.exe: gvdevice_devil:(.text+0x238): undefined reference to __imp_iluErrorString