GDK plugin: add missing linking against gvc
Without this change, an upcoming commit that sets HAVE_PANGOCAIRO to 1
when PangoCairo is found with CMake, would cause this error on macOS:

[ 72%] Linking C shared library libgvplugin_gdk.dylib
Undefined symbols for architecture x86_64:
  "_gvusershape_file_access", referenced from:
      _gdk_loadimage in gvloadimage_gdk.c.o
  "_gvusershape_file_release", referenced from:
      _gdk_loadimage in gvloadimage_gdk.c.o
  "_gvwrite", referenced from:
      _writer in gvdevice_gdk.c.o
ld: symbol(s) not found for architecture x86_64